### ISSUE TITLE
🚀 建议容器化| [Feature]Some feature...

### ISSUE THREAD

**Issue by bughoho** [ptonlix/LangChain-SearXNG#3]
#### 您使用的场景？ | 1. Your usage scenarios?
docker容器部署
#### 您期望的结果是怎样的？ | 2. What is your expected outcome?
集成的docker-compose

建议用将项目容器化，干净卫生😄，可以用docker-compose整合AI和SearXNG，目前的方式在NAS上配置不太方便。

**Comment by ptonlix** [comment]
感谢反馈，已列入计划

**Comment by ptonlix** [comment]
已支持docker-compose整合AI和SearXNG

**Comment by ptonlix** [comment]
已支持docker-compose整合AI和SearXNG
